### ISSUE TITLE
update vue (and other packages) to latest

### ISSUE THREAD

**Issue by nylira** [cosmos/explorer#2]
There are a lot of improvements to Vue that impact performance and make development easier. We should implement it.

- [ ] use the latest version of vue-cli to generate a new backbone for the project, then move all the `./app` code over
- [ ] update other packages
- [ ] use Prettier

**Comment by okwme** [comment]
should we be using vue-cli 3.0 which is still in beta?  

i used it recently in another project and was disappointed to find that webpack had been abstracted away into a config file. i've always been happy that while searching for webpack resources results weren't restricted to vue. for better or worse having them hidden feels more like `create-react`.  

otherwise i really enjoy having all the project settings abstracted into one place.

those are my two cents, either way i'm happy to move ahead with whichever version is most appropriate.

**Comment by nylira** [comment]
I enjoy the change in vue-cli 3.0. I upgraded our websites to it (cosmos.network and tendermint.com) and in both cases it managed to reduce the lines of code we have to manage by about 10%. I did run into the issue you mentioned about how the webpack config no longer applies to other projects, but the new syntax isn't too bad [1]. And we only rarely have to configure webpack.

[1] https://github.com/cosmos/cosmos.network/blob/develop/vue.config.js

**Comment by zhiqiang-bianjie** [comment]
Hi, can I take this task?
